#!/bin/bash  


clear


cd graphs
rm *.png
cd ..

cd energies
rm *.txt
cd ..

cd graphsEnergie
rm *.png
cd ..

cd graphsAires
rm *.png
cd ..



cd aires
rm *.txt
cd ..

cd positions
rm *.txt
cd ..




