#!/bin/bash  


clear


cd aires
rm *.txt
cd ..

cd positions
rm *.txt
cd ..

cd energies
rm *.txt
cd ..


cd graphPositions
rm *.png
cd ..


cd graphsEnergie
rm *.png
cd ..

cd graphsAires
rm *.png
cd ..





