#!/bin/bash  

cd positions

if [ "$3" == 'Verlet' ] || [ "$3" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphPositions/Verlet_sim3D_$2 ans $1pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 Verlet_data*.txt")
		LABEL = system("ls -1 Verlet_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 3:2:4 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi



if [ "$3" == 'Cromer' ] || [ "$3" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphPositions/EulerCromer_sim3D_$2 ans $1pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 EulerCromer_data*.txt")
		LABEL = system("ls -1 EulerCromer_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 3:2:4 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi



if [ "$3" == 'Euler' ] || [ "$3" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphPositions/Euler_sim3D_$2 ans $1pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 Euler_data*.txt")
		LABEL = system("ls -1 Euler_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 3:2:4 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

if [ "$3" == 'RK4' ] || [ "$3" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphPositions/RK4_sim3D_$2 ans $1pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 RK4_data*.txt")
		LABEL = system("ls -1 RK4_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 3:2:4 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

cd ..
