#!/bin/bash  

ts=$(date +%s%N)  



clear
bash cleaning

cd src
if [ "$5" == '-new' ]; then
	make clean
	make
fi
$a = 'vitesseLiberation'
./mecaCeleste $1 $2 $3 $4 $6 $7 $a $9 $10
cd ..


bash gnuplotPositions $2 $3 $6
bash gnuplotAires $2 $3 $6
bash gnuplotEnergies $2 $3

tt=$((($(date +%s%N) - $ts)/1000000)); echo "Script total time: $tt [ms]"
