#!/bin/bash  

ts=$(date +%s%N)  



clear
bash cleaning


cd src
make clean
make
./mecaCeleste 'liberation' $1 $2 $3
cd ..


tt=$((($(date +%s%N) - $ts)/1000000)); echo "Script total time: $tt [ms]"
