#!/bin/bash  

ts=$(date +%s%N)  



clear
bash cleaning

cd src
make clean
make

./mecaCeleste 'simuler' $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12}
cd ..


bash gnuplotPositions $2 $3 $5
bash gnuplotAires $2 $3 $5
bash gnuplotEnergies $2 $3

tt=$((($(date +%s%N) - $ts)/1000000)); echo "Script total time: $tt [ms]"
