#!/bin/bash  

ts=$(date +%s%N)  



clear
bash cleaning

cd src
if [ "$5" == '-new' ]; then
	make clean
	make
fi
./mecaCeleste $1 $2 $3 $4 $6 $7
cd ..



cd positions

if [ "$6" == 'Verlet' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphs/Verlet_sim3D_$3 ans $2pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 Verlet_data*.txt")
		LABEL = system("ls -1 Verlet_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 2:1:3 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi



if [ "$6" == 'Cromer' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphs/EulerCromer_sim3D_$3 ans $2pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 EulerCromer_data*.txt")
		LABEL = system("ls -1 EulerCromer_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 2:1:3 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi



if [ "$6" == 'Euler' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphs/Euler_sim3D_$3 ans $2pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 Euler_data*.txt")
		LABEL = system("ls -1 Euler_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 2:1:3 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

if [ "$6" == 'RK4' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
		  	set term pngcairo size 3000,1600
		  	set output "../graphs/RK4_sim3D_$3 ans $2pts.png"
		set xlabel "Axis x, (en $4)"
		set ylabel "Axis y, (en $4)"
		set zlabel "Axis z, (en $4)"
		FILES = system("ls -1 RK4_data*.txt")
		LABEL = system("ls -1 RK4_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		splot for [i=1:words(FILES)] word(FILES,i) u 2:1:3 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

cd ..



cd aires

if [ "$6" == 'Euler' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
  	set term pngcairo size 3000,1600
  	set output "../graphsAires/Euler_aires_$3 ans $2pts.png"
		set datafile separator "\t"
		set xlabel "Temps"
		set ylabel "Erreur relative sur l'aire"
		set format y "%.0s*10^{%T}"
		FILES = system("ls -1 Euler_data*.txt")
		LABEL = system("ls -1 Euler_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		plot for [i=1:words(FILES)] word(FILES,i) u 1:2 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

if [ "$6" == 'Cromer' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
  	set term pngcairo size 3000,1600
  	set output "../graphsAires/EulerCromer_aires_$3 ans $2pts.png"
		set datafile separator "\t"
		set xlabel "Temps"
		set ylabel "Erreur relative sur l'aire"
		set format y "%.0s*10^{%T}"
		FILES = system("ls -1 EulerCromer_data*.txt")
		LABEL = system("ls -1 EulerCromer_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		plot for [i=1:words(FILES)] word(FILES,i) u 1:2 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

if [ "$6" == 'Verlet' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
  	set term pngcairo size 3000,1600
  	set output "../graphsAires/Verlet_aires_$3 ans $2pts.png"
		set datafile separator "\t"
		set xlabel "Temps"
		set ylabel "Erreur relative sur l'aire"
		set format y "%.0s*10^{%T}"
		FILES = system("ls -1 Verlet_data*.txt")
		LABEL = system("ls -1 Verlet_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		plot for [i=1:words(FILES)] word(FILES,i) u 1:2 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

if [ "$6" == 'RK4' ] || [ "$6" == 'all' ]; then
	gnuplot -persist <<-EOFMarker
  	set term pngcairo size 3000,1600
  	set output "../graphsAires/RK4_aires_$3 ans $2pts.png"
		set datafile separator "\t"
		set xlabel "Temps"
		set ylabel "Erreur relative sur l'aire"
		set format y "%.0s*10^{%T}"
		FILES = system("ls -1 RK4_data*.txt")
		LABEL = system("ls -1 RK4_data*.txt | sed -e 's/data//' -e 's/.dat//'")
		plot for [i=1:words(FILES)] word(FILES,i) u 1:2 title word(LABEL,i) with lines noenhanced
	EOFMarker
fi

cd ..


cd energies
	gnuplot -persist <<-EOFMarker
  	set term pngcairo size 3000,1600
  	set output "../graphsEnergie/energieMeca_$3 ans $2pts.png"
		set datafile separator "\t"
		set xlabel "Temps"
		set ylabel "Erreur relative sur l'énergie mécanique totale"
		set format y "%.0s*10^{%T}"
		FILES = system("ls -1 *.txt")
		LABEL = system("ls -1 *.txt | sed -e 's/data//' -e 's/.dat//'")
		plot for [i=1:words(FILES)] word(FILES,i) u 1:2 title word(LABEL,i) with lines noenhanced
	EOFMarker
cd ..

tt=$((($(date +%s%N) - $ts)/1000000)); echo "Script total time: $tt [ms]"
